import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>MoneyHelper Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="text-4xl font-bold mb-3">
          Welcome to MoneyHelper Tools!
        </h1>
        <ul className="">
          <li>
            <Link href="/stamp-duty-calculator">
              <a className="text-lg text-gray-700 underline">
                Stamp Duty Calculator
              </a>
            </Link>
          </li>
          <li>
            <Link
              href="/compare-accounts"
              className="text-lg text-gray-700 underline"
            >
              <a className="text-lg text-gray-700 underline">
                Compare Accounts
              </a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
