import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MoneyHelper Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MoneyHelper Tools!</h1>
        <ul className={styles.grid}>
          <li>
            <Link href="/stamp-duty-calculator">Stamp Duty Calculator</Link>
          </li>
          <li>
            <Link href="/graph-ql-integration">GraphQL Integration</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
