import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MoneyHelper Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MoneyHelper Tools!</h1>

        <div className={styles.grid}>
          <a href="/stamp-duty-calculator" className={styles.card}>
            <h2>Stamp Duty Calculator</h2>
            <p>Calculate Stamp Duty</p>
          </a>
        </div>
      </main>
    </div>
  );
}
